apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-h1vq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0075-tenant/tkrw-pr714-0075-0075-app/devfile-sample-h1vq@sha256:d8abc54141bbc7faabf1fb190d1cc07954e6c3ad08e145e169316df9a28760aa
        name: my-nodejs
        resources: {}
status: {}
